[tool.poetry]
name = "EDHD"
version = "0.1.0"
description = ""
authors = ["KRT3186 <t.kropp@primeo-energie.ch>"]
readme = "README.md"

packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
ipython = "^8.16.1"
ipykernel = "^6.25.2"
python = "^3.12"
flask = "3.1.0"
requests = "2.32.3"
pytest = "8.3.3"
pydantic = "^2.10.3"
pandas = "^2.2.3"
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
